### ISSUE TITLE
I can't import the module on Prestashop 1.7

### ISSUE THREAD

**Issue by srbarrios** [dim00z/gshoppingflux#32] opened 2017-06-24 09:01 UTC
Should it work? Or this module doesn't support yet Prestashop 1.7?

**Comment by Casper-O** [comment] 2017-06-24 10:34
I have not tested the module on 1.7 and I don't think dim00z did ether.

There happen a lot of changes from 1.6 to 1.7 so it's possible this module don't work.

**Comment by edusanch913** [comment] 2017-11-07 19:42
Any ones know if the last version works correctly in 1.7.2

**Comment by Casper-O** [comment] 2017-11-07 19:43
I had reports that it should work in 1.7.2.X - But I have not tested myself.

**Comment by edusanch913** [comment] 2017-11-07 19:50
I already tested and it seems to work well, but it has an issue that the column of ID, if I dont write a Reference in the product, automatically it gives in the FEED the Product ID and it is correct, the problem is if I write in some products a Reference it takes in the Feed that as the Product ID and in Merchant Center dont match and Merchant Center dont approve that products. Do you know how to solve it? Thank you very much!

**Comment by Casper-O** [comment] 2017-11-16 12:23
Hi @edusanch913 Glad to hear it works on 1.7 for you also. but what you descripe seems to be a diffrent issue.

If you did not find a solution, please make a new issue report regarding this. I will close this one

**Closed by Casper-O** 2017-11-16 12:23 UTC
